### ISSUE TITLE
Integration of static number with trigonometric functions

### ISSUE THREAD

**Issue by oschulz** [perrutquist/StaticNumbers.jl#10]
Currently, StaticNumbers defines

```julia
@inline static(x::Irrational) = x
```

But if irrationals would be wrapped too, we could have `sin(static(π)) == static(0)`, without type piracy in respect to Base.

**Comment by perrutquist** [comment]
True. I had not thought about that.

**Comment by perrutquist** [comment]
Allowing static Irrationals is not as easy as just removing that one line. A number of operations on irrationals do not work via promotion/conversion and so would have to have wrappers.
For example:
```
isfinite(static(π))
isnan(static(π))
static(π) == π
```

**Comment by oschulz** [comment]
Yes - do you think it would get too unwieldy?

**Comment by perrutquist** [comment]
I think it's possible. Tests pass on the master branch at the moment, but I'll have to look through the code for Base.Irrational to see if there's anything that I missed.

**Comment by perrutquist** [comment]
The just-released version 0.3.3 of StaticNumbers will support `static(π)` although some operations on it will error for Julia versions < 1.5 due to `one(π)` not being implemented in Base.

**Comment by oschulz** [comment]
Thanks!

I've joined in lobbying for some kind of static one/zero type in Base on JuliaLang/julia#34003 - if we had that, some things could integrate better with StaticNumbers, I think.

**Comment by perrutquist** [comment]
For a static one/zero type, there's also [Zeros.jl](https://github.com/perrutquist/Zeros.jl).

**Comment by oschulz** [comment]
Oh, lol that's great - I was about to prototype a package like that! :-)

I had been thinking about having special singletons for +- infinity too. Do you think that's possible? Or maybe also one for NaN, so that the `Zero` doesn't have to be a strong one. Do you think something like that's feasible? Or would it get too complex, and that's why you decided on a strong zero?

**Comment by perrutquist** [comment]
Zeros.jl started out with only `Zero`. Then it seemed like a good idea to also have `One`, since 1 is to * what 0 is to +. Then I thought about including `Inf`, but then it would also be necessary to have `MinusInf`, and if we have that it would be logical to also have `MinusOne`... This is when I decided to write StaticNumbers.jl.

**Comment by oschulz** [comment]
Yep, I fully understand. :-) I really like your two packages, also the fact that they come in lightweight and fully-fledged. I'm thinking about using this in BAT.jl, esp. `One()` to handle uniform statistical weights (with a performance boost).
