### ISSUE TITLE
What's the reason for making all operations on static types return non-static types?

### ISSUE THREAD

**Issue by nsajko** [perrutquist/StaticNumbers.jl#16]
The following quote from the documentation is quite surprising:

> By default, any operation on a `Static` will result in a non-`Static` type. For example, `static(2)+static(2)` gives `4`, not `static(4)`.

What is the reasoning/purpose behind this weird behavior?

**Comment by perrutquist** [comment]
The reason for this is to avoid creating large number of types by mistake.

For example, consider the following function
```julia
"call f(s), f(2s), f(3s) ... f(1000000s)"
function a_million_calls_to_f(s)
    i = s
    for k+1:1000000
       f(i)
       i += s
    end
end
```

If Static+Static yielded a Static, then calling ` a_million_calls_to_f(static(1))` would create a million different static numbers, and cause `f` to be re-compiled for each of them.

**Comment by nsajko** [comment]
OK, thank you.
